"""empty message

Revision ID: 1fa89150b5cf
Revises: 
Create Date: 2023-03-08 20:16:24.040452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fa89150b5cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'user', ['photo'])
    op.add_column('user_has_booking', sa.Column('calendar_booking_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user_has_booking', ['url'])
    op.create_foreign_key(None, 'user_has_booking', 'calendar_booking', ['calendar_booking_id'], ['id'])
    op.drop_column('user_has_booking', 'id')
    op.drop_column('user_has_booking', 'booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_has_booking', sa.Column('booking', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user_has_booking', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user_has_booking', type_='foreignkey')
    op.drop_constraint(None, 'user_has_booking', type_='unique')
    op.drop_column('user_has_booking', 'calendar_booking_id')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'photo')
    # ### end Alembic commands ###
