"""empty message

Revision ID: 6c1454f2ad4d
Revises: 
Create Date: 2023-02-27 18:46:06.381249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1454f2ad4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_day', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_booking', schema=None) as batch_op:
        batch_op.drop_column('visit_day')

    # ### end Alembic commands ###
