"""empty message

Revision ID: a44b371118e4
Revises: 
Create Date: 2023-02-27 18:03:01.706623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44b371118e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_booking', schema=None) as batch_op:
        batch_op.drop_column('visit_day')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['photo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('photo')

    with op.batch_alter_table('calendar_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_day', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
