"""empty message

Revision ID: b9b108d414ce
Revises: 
Create Date: 2023-02-27 17:43:58.150252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b108d414ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_day', sa.String(length=120), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_photo_key', type_='unique')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_photo_key', ['photo'])

    with op.batch_alter_table('calendar_booking', schema=None) as batch_op:
        batch_op.drop_column('visit_day')

    # ### end Alembic commands ###
