"""empty message

Revision ID: ca460b3f58a3
Revises: d7b96f4285ae
Create Date: 2023-02-03 18:11:14.578556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca460b3f58a3'
down_revision = 'd7b96f4285ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('resident_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'resident', ['resident_id'], ['id'])
    op.add_column('user_has_booking', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_has_booking', 'user', ['user_id'], ['id'])
    op.drop_column('user_has_booking', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_has_booking', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_has_booking', type_='foreignkey')
    op.drop_column('user_has_booking', 'user_id')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'resident_id')
    # ### end Alembic commands ###
